### ISSUE TITLE
Problem with Emitter

### ISSUE THREAD

**Issue by bleeuwen** [pwbrown/react-native-ios-network-audio#2]
The described code (with new option to check for the end) did not work
I corrected it as follows:

var NativeAppEventEmitter=require('RCTNativeAppEventEmitter');

var subscription = NativeAppEventEmitter.addListener(
    'AudioEnded',
    (trigger) => {console.log(trigger.event)}
);

**Comment by jchoi18** [comment]
I created a PR to fix this: https://github.com/pwbrown/react-native-ios-network-audio/pull/4

**Comment by pwbrown** [comment]
Thanks for the code change!
