### ISSUE TITLE
How do you link this module into build phase?

### ISSUE THREAD

**Issue by donedgardo** [pwbrown/react-native-ios-network-audio#3]
The Readme says to include the .h and .m file inside the project is that there is to it?
No rnpm linking or any configuration needed... its not working for me, Im new to Native Modules. Help Wanted plz and ty!!!

**Comment by pwbrown** [comment]
Hey donedgardo, haven't messed with this package in a while, so I went ahead and rewrote my test application for you.  The readme has detailed instructions on how I was able to get it to work, and you can test it for yourself.  I will most likely update the readme for this repository with better instructions, and documentation on the es6 script. https://github.com/pwbrown/Audio-Player-Test-Application

**Comment by donedgardo** [comment]
I got it to work! Ty, my problem was how I imported the audio variable with es6. Ty for the test app and the instruction for background enabled audio!!
